ablog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('blog.urls'), name='blog'),
    path('accounts/', include('django.contrib.auth.urls'), name='login'),
    path('admin/', admin.site.urls),
    path('calendar/', include('speedway_calendar.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'blog.views.handler403'

blog/urls.py
from django.urls import path
from .views import HomeView, PostDetailsView, AddPostView, DeletePostView, UpdatePostView, AddCommentView


urlpatterns = [
    path('', HomeView.as_view(), name='blog_home'),
    path('post/<slug:slug>', PostDetailsView.as_view(), name='details'),
    path('add_post', AddPostView.as_view(), name='add_post'),
    path('post/<int:pk>/delete', DeletePostView.as_view(), name='delete'),
    path('post/<int:pk>/update', UpdatePostView.as_view(), name='update'),
    path('post/<int:pk>/add_comment', AddCommentView.as_view(), name='add_comment')
]

speedway_calendar/urls.py
from django.urls import path
from .views import HomeView, TaskDetailsView, addTaskView

urlpatterns = [
    path('', HomeView.as_view(), name='calendar_home'),
    path('task/<int:pk>', TaskDetailsView.as_view(), name='calendar_details'),
    path('add_task', addTaskView.as_view(), name='add_task')
]

speedway_calendar/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Task(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    place = models.CharField(max_length=255)
    match_date = models.DateTimeField()
    description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + ', ' + str(self.author)

    def get_absolute_url(self):
        return reverse('calendar_details', args=[self.id])

speedway_calendar/forms.py
import datetime

from django import forms

from .models import Task

class DateInput(forms.DateInput):
    input_type = 'date'
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ('title', 'place', 'match_date', 'description')

        labels = {
            'title': 'Tytuł',
            'place': 'Miejsce',
            'match_date': 'Data',
            'description': 'Opis'
        }

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'place': forms.TextInput(attrs={'class': 'form-control'}),
            'match_date': DateInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'})
        }

speedway_calendar/views.py
from django.contrib.sites import requests
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.http import HttpResponseNotFound
import requests

from .forms import TaskForm
from .models import Task
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class HomeView(ListView):
    model = Task
    template_name = 'speedway_calendar/home.html'
    def get_queryset(self):
        return Task.objects.filter(author__username=self.request.user)

class TaskDetailsView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'speedway_calendar/task_details.html'
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = self.get_object()
        place = task.place

        url = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=153986837855671edcb6d89de1d74d34'

        try:
            response = requests.get(url.format(place))  # request the API data and convert the JSON to Python data types
            city_weather = response.json()
            celsius_temperature = round((((city_weather['main']['temp']) - 32) * 5/9), 1)

            weather = {
                'temperature': celsius_temperature,
                'description': city_weather['weather'][0]['description'],
                'icon': city_weather['weather'][0]['icon']
            }

            context['weather'] = weather

            return context
        except:
            return {}
class addTaskView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = 'speedway_calendar/add_task.html'
    form_class = TaskForm
    login_url = reverse_lazy('login')
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

speedway_calendar/templates/speedway_calendar/add_task.html
{% extends 'base.html' %}

{% block title %}
    Dodaj nowy plan
{% endblock %}

{% block content %}
    <h1>Dodaj sobie plan wyjazdowy ziomeczku</h1>
    <div class="container d-flex justify-content-center">
        <form method="POST">
        {% csrf_token %}
        {{ form }}
        <div class="d-grid">
            <button type="submit" class="btn btn-primary m-2">Dodaj</button>
        </div>
        </form>
    </div>
{% endblock %}

speedway_calendar/templates/speedway_calendar/home.html
{% extends 'base.html' %}

{% block title %}
    Planer zawodów
{% endblock %}

{% block content %}
    <h1>:DDDDDDDDDDDDDDDDDD</h1>
    <ul class="list-group">
        {% for task in task_list %}
            <li class="list-group-item">
                <b>Tytuł:</b> <a href="{% url 'calendar_details' task.pk %}">{{ task.title }}</a><br>
                <b>Autor:</b> {{ task.author }}<br>
                <b>Opis:</b> {{ task.description }}<br>
                <b>Data zawodów:</b> {{ task.match_date|date:'Y-m-d, G:i' }}<br>
                <b>Utworzono:</b> {{ task.created_at|date:'Y-m-d, G:i' }}<br>
                {% if user == post.author %}
                    <a href="#" class="update">Edytuj</a>
                    <a href="#" class="delete">Usuń</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

speedway_calendar/templates/speedway_calendar/task_details.html
{% extends 'base.html' %}
{% block title %}
    "{{ task.title }}"
{% endblock %}

{% block content %}
    <h1>{{ task.title }}</h1>
    <h2>{{ task.place }}, {{ task.match_date|date:'Y-m-d, G:i' }}</h2>
    <p>{{ task.description }}</p>
    <p>{{ weather.temperature }}</p>
    <p>{{ weather.description }}</p>
    <img src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="weather image">
    <br><br>
    <button type="button" class="btn btn-primary"><a href="{% url 'calendar_home' %}">Wróć do listy</a></button>
{% endblock %}